version: '2'

jobs:

  test-chrome:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker pull cypress/included:9.7.0
    - run:
        command: docker-compose up
        no_output_timeout: 3m

workflows:
  version: '2'
  build:
    jobs:
    # - test-electron
    - test-chrome
    # - test-firefox
