version: '3'

services:
  e2e-chrome:
    image: "cypress/included:9.7.0"
    container_name: cypress
    # "cypress/included" images have entrypoint set to globally installed cypress
    # so the command can simply add any arguments
    command: "--browser chrome"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
